version: "3.3"
services:
 transmission-openvpn:
    volumes:
        - /mnt/usr/data/downloads/:/data/completed/
        - /etc/localtime:/etc/localtime:ro
    environment:
        - PUID=$PUID
        - PGID=$PGID
        - CREATE_TUN_DEVICE=true
        - OPENVPN_PROVIDER=NORDVPN
        # - OPENVPN_CONFIG=default
        - NORDVPN_COUNTRY=US
        - NORDVPN_CATEGORY=legacy_p2p
        - NORDVPN_PROTOCOL=udp
        - OPENVPN_USERNAME=$user
        - OPENVPN_PASSWORD=$password
        - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
        - WEBPROXY_ENABLED=false
        - LOCAL_NETWORK=192.168.0.0/16
        - TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED=false
        - DNS=8.8.8.8,8.8.4.4
    cap_add:
        - NET_ADMIN
    logging:
        driver: json-file
        options:
            max-size: 10m
    ports:
        - 9091:9091
        - 9117:9117
        - 7878:7878
        - 8989:8989
        - 8686:8686
        - 5299:5299
    restart: always
    image: haugene/transmission-openvpn

 jackett:
    image: linuxserver/jackett
    container_name: jackett
    network_mode: service:transmission-openvpn
    environment:
        - PUID=$PUID
        - PGID=$PGID
        - TZ=America/New_York
        - AUTO_UPDATE=true #optional
        - RUN_OPTS=#optional
    volumes:
        - /docker/jackett:/config
        #Jackett only needs config
    restart: unless-stopped

 radarr:
    image: linuxserver/radarr
    network_mode: service:transmission-openvpn
    container_name: radarr
    environment:
        - PUID=$PUID
        - PGID=$PGID
        - TZ=America/New_York
        - UMASK_SET=022 #optional
    volumes:
        - /docker/radarr/:/config/
        - /mnt/usr/data/movies/:/data/movies/
        - /mnt/usr/data/downloads/:/data/completed/
        #- /mnt/usr/data:/data
    restart: unless-stopped

 sonarr:
    image: linuxserver/sonarr
    network_mode: service:transmission-openvpn
    container_name: sonarr
    environment:
        - PUID=$PUID
        - PGID=$PGID
        - TZ=America/New_York
        - UMASK_SET=022 #optional
    volumes:
        - /docker/sonarr:/config
        - /mnt/usr/data:/data
    restart: unless-stopped

 plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - VERSION=docker
      - PLEX_CLAIM=$PLEX_CLAIM
    volumes:
      - /docker/plex/:/config
      - /mnt/usr/data/tv/:/tv
      - /mnt/usr/data/movies/:/movies
    restart: unless-stopped
